# Generated by Django 2.0.2 on 2018-05-22 03:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('body', models.TextField()),
                ('title', models.CharField(max_length=200)),
                ('rating', models.IntegerField()),
                ('user', models.ForeignKey(on_delete='CASCADE', related_name='reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('user', 'title')},
        ),
    ]
